/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: Naked Singularity (https://sketchfab.com/nakedsingularity)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-pipette-laboratory-low-poly-6c8ede9361f047df88dca68029249e22
Title: FREE Pipette | Laboratory | Low poly
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-3.554, 17.371, 0]} rotation={[-Math.PI, -0.964, -Math.PI]}>
          <mesh geometry={nodes.Blue_piette_NakedSingularity_plastic_0.geometry} material={materials.plastic} />
          <mesh geometry={nodes.Blue_piette_NakedSingularity_glass_0.geometry} material={materials.glass} />
        </group>
        <group position={[1.823, 17.371, -1.788]} rotation={[-Math.PI, -1.052, -Math.PI]}>
          <mesh geometry={nodes.Red_piette_NakedSingularity_plastic_red_0.geometry} material={materials.plastic_red} />
          <mesh geometry={nodes.Red_piette_NakedSingularity_glass_0.geometry} material={materials.glass} />
        </group>
        <group position={[-2.055, 1.538, 8.034]} rotation={[1.531, -0.042, 0.742]}>
          <mesh geometry={nodes.Red_piette_NakedSingularity1_plastic_red_0.geometry} material={materials.plastic_red} />
          <mesh geometry={nodes.Red_piette_NakedSingularity1_glass_0.geometry} material={materials.glass} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
